<!-- GMAPS START -->
<style type="text/css">
html { height: 100%; }
body { height: 100%; margin: 0px; padding: 0px; }
#map_canvas { height: 100%; }
#map_canvas2 { height: 100%; }
</style>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
function initialize(Lat, Lon, obj) {
	var myLatlng = new google.maps.LatLng(Lat, Lon);
	var myOptions = {
		zoom: 16,
		center: myLatlng,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	}
	var map = new google.maps.Map(document.getElementById(obj), myOptions);

	var image = '/_assets/images/site/marker.png';
	var beachMarker = new google.maps.Marker({
		position: myLatlng,
		map: map/*,
		icon: image*/
	});

	google.maps.event.addListener(beachMarker, 'click', function() {
		infowindow.open(map, beachMarker);
	});
}

$(function() {
	initialize($("#map_canvas").data("lat"), $("#map_canvas").data("lon"), $("#map_canvas").attr("id"));
});
</script>
<!-- GMAPS END -->
<div id="CONTATO" class="pagina_detalhe">
	<h1>Contato</h1>
	<div class="row">
		<div class="col-xs-6">
			<div class="text_format"><?= $this->oPagina->TEXTO?></div>
			<div id="map_canvas" class="" style="width:100%; height:270px" data-lat="-1.443560" data-lon="-48.484750"></div>
		</div> <!-- .col-xs-6 -->
		<div class="col-xs-6">
			<form action="" method="post" class="" id="FRM-CONTATO">
				<input type="hidden" name="ASSUNTO" id="ASSUNTO" value="Contato do Site"/>
				<div class="form-group">
					<label>Nome:</label>
					<input type="text" class="validate[required,length[0,100]] form-control" placeholder="NOME" name="NOME" id="NOME" value="" />	
				</div>
				<div class="form-group small">
					<label>Telefone:</label>
					<input type="text" class="validate[required,length[0,100]] form-control" placeholder="TELEFONE" name="TELEFONE" id="TELEFONE" value="" />
				</div>
				<div class="form-group">
					<label>E-mail:</label>
					<input type="text" class="validate[required,length[0,100]] form-control" placeholder="EMAIL" name="EMAIL" id="EMAIL" value=""  />
				</div>
				<div class="form-group">
					<label>Mensagem:</label>
					<textarea class="validate[required,length[0,100]] placeholder form-control" rows="6" name="MENSAGEM" id="MENSAGEM"></textarea>			
				</div>
				<div align="right" class="form-group">
					<button type="submit" class="btn btn-primary">Enviar</button>
				</div>
			</form>
		</div> <!-- .col-xs-6 -->
	</div> <!-- .row -->
</div>
