<h1>Configuração</h1>
<script type="text/javascript">

    function loadImagem2(){
        $("#UPLOAD2_CONTEUDO").load('/adm/auxiliar/arquivo/ID_PAGINA/<?= $this->ID ?>/TABELA/config_manutencao');
    }
    function loadImagem3(){
        $("#UPLOAD3_CONTEUDO").load('/adm/auxiliar/arquivo/ID_PAGINA/<?= $this->ID ?>/TABELA/config_favicon');
    }
    $(function(){
        loadImagem2();
        loadImagem3();
        $("#PRE_VISUALIZAR").click(function(){
            var form = $(this).parents('form');
            function abre(){
                window.open('/pagina/<?= $this->TIPO ?>detalhe/ID/<?= $this->ID ?>');
            }
            $.post('/adm/pagina/jSavePrevisualiza/', form.serializeArray(), function(data){
                abre();
            }, 'json');
        });
        
    });
</script>
<style type="text/css">
    .PREV{border: 10px solid grey;display: none;width: 700px}
</style>
<?= $this->form ?>
