<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <title>Error</title>
    </head>
    <body>
        <? if ($this->tipoErro == 1): ?>
            <h1>Ocorreu um erro</h1>
            <h2><?php echo $this->message ?></h2>

            <h3>Informações sobre o Erro:</h3>
            <p>
                <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
            </p>

            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?></pre>

            <h3>Parâmetros Enviados:</h3>
            <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
            <br/><br/>
        <? elseif ($this->tipoErro == 2): ?>

            <h1>Ocorreu um erro</h1>
            <h2>
                <?= $this->exception ?>
            </h2>
            <h3>Parâmetros Enviados:</h3>
            <pre>
                <?php
                foreach ($this->request as $i => $v) {
                    echo "$i: $v <br/>";
                }
                ?>
            </pre>
            <br/><br/>

        <? else: ?>

            <br/><br/>
            <center>
                <? if ($this->error == 404): ?>
                    <h3>A página não foi encontrada, <a href="/">clique aqui</a> para voltar a página inicial</h3>
                <? else: ?>
                    <h3>Ocorreu um erro no site. Mas não se preocupe, nosso engenheiro foi notificado por e-mail e já está cuidando disso.</h3>
                <? endif; ?>
                <img src="/imagem/site/error-<?= $this->error ?>.jpg" />
            </center>

        <? endif; ?>
    </body>
</html>