<? $data = ZC_Util::getData(); ?>
<?// Busines_Util::debug($data) ?>
<? if ($this->tipoErro == 1): ?>
    <h1>Ocorreu um erro</h1>
    <h2><?php echo $this->message ?></h2>

    <h3>Informações sobre o Erro:</h3>
    <p>
        <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>

    <h3>Parâmetros Enviados:</h3>
    <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
    <br/><br/>
    <center>
        <img src="/imagem/site/erro.gif" />
    </center>
<? elseif ($this->tipoErro == 2): ?>
    <h1>Ocorreu um erro</h1>
    <h2>
        <?= $this->exception ?>
    </h2>
    <h3>Parâmetros Enviados:</h3>
    <pre>
        <?php
        foreach ($this->request as $i => $v) {
            echo "$i: $v <br/>";
        }
        ?>
    </pre>
    <br/><br/>
    <center>
        <img src="/imagem/site/erro.gif" />
    </center>
<? else: ?>
    <br/><br/>
    <center>
        <img src="/imagem/site/erro.gif" />
    </center>
<? endif; ?>
