
<script type="text/javascript">
    function loadImagem(){
        $("#UPLOAD_CONTEUDO").load('/adm/auxiliar/arquivo/ID_PAGINA/<?= $this->ID ?>');
    }
    $(function(){
        
        $("#TITULO").charCount({
            allowed: 60,		
            warning: 20,
            counterText: 'Restam: '	
        });
        $("#RESUMO").charCount({
            allowed: 144,		
            warning: 20,
            counterText: 'Restam: '	
        });
        
        loadImagem();
        $("#PRE_VISUALIZAR").click(function(){
            var form = $(this).parents('form');
            function abre(){
                window.open('/pagina/<?= $this->TIPO ?>detalhe/ID/<?= $this->ID ?>');
            }
            $.post('/adm/pagina/jSavePrevisualiza/', form.serializeArray(), function(data){
                abre();
            }, 'json');
        });
        <? if ($this->TAGSV) { ?>
            $(function(){
                var sampleTags = <?= $this->tags ?>;
                $('#TAG').tagit({
                    availableTags: sampleTags,
                    allowSpaces: true
                });
            });
        <? } ?>
    });
</script>
<style type="text/css">
    SPAN.tagMatches {
        margin-left: 10px;
    }

    #TAG{
        display: inline-table;
    }
    SPAN.tagMatches SPAN {
        padding: 2px;
        margin-right: 4px;
        background-color: #0000AB;
        color: #fff;
        cursor: pointer;
    }
    #cke_TEXTO{
        width: 460px;
    }
</style>
<?= $this->form ?>
