<div class="extra-footer">
	<div id="RODAPE" class="site-footer container">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6 text-center">
				<a href="http://www.libradesign.com.br" target="_blank" title="Desenvolvido por Libra Design +Tech">
					<img src="/imagem/library/assinatura_horizontal_positivo.png" alt="Libra Design +Tech" />
				</a>
			</div>
			<div class="col-md-3 text-right">Copyright &COPY; Libra Design 2011</div>
		</div>
	</div> <!-- #RODAPE -->
</div> <!-- .extra-footer -->