<h3>Comentários</h3>
<form method="POST" action="/">
	
</form>
<div class="form-group">
	<textarea class="form-control" name="TEXTO" rows="4" cols="66"></textarea>
</div>
<div class="form-group">
	<button type="submit" class="btn btn-default">Enviar</button>
</div>

<div>
	<div>
		<h4>Luiz (29/08/2010  15:30:10)</h4>
	</div>
	<p>
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
		industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
		and scrambled it to make a type specimen book. It has survived not only five centuries, but also the
	</p>
</div>