<!-- O código abaixo é para exibição de popups. Trocar apenas a src para a imagem desejada.-->
<script type="text/javascript">
    $(function(){
        showPopup();
    });
</script>
<div class="popup">
	<div class="popup-content">
		<a href="javascript:void(0);" class="popup-close" title="Clique para fechar"><span>x</span>fechar</a>
		<a href="javascript:void(0);" class="popup-img"><img src="/imagem/popup/copa-2014.png" alt="Assista aos jogos do Brasil no Armazém" ></a>
	</div>
</div>