<? $this->mensagem = ZC_Alerta::get();?>
<? if($this->mensagem): ?>
	<style type="text/css">
		.jMensagemAlerta .mensagem{
			display:none;z-index:9999;background:#432239;margin-left:-180px;left:50%;top:30% !important;margin-top:-65px;
			min-height:130px;min-width: 360px;box-shadow: 0px 0px 3px #000;-webkit-box-shadow: 0 0 33px #e1e1e1;-moz-box-shadow: 0 0 3px #000;
			position: relative;
			-webkit-border-radius: 5px;	-moz-border-radius: 5px;border-radius: 5px;
		}
		.jMensagemAlerta .mensagem > div.left{height: 40px;margin: 20px 0 0 20px;width: 46px;}
		.jMensagemAlerta .mensagem > div.right{float: right;padding-right: 15px;width: 272px;}
		.jMensagemAlerta .mensagem > div h1{margin-top: 0px;padding: 15px 0 0 0;color: #f8f2e8;font-size: 17px;font-weight: bolder;height: 23px;text-align: left;}
		.jMensagemAlerta .mensagem > div > p{font-size: 14px;font-weight: bolder;text-align: left;color: #f8f2e8;width: 277px;text-align: justify;}
		.jMensagemAlerta .mensagem > .alerta_continuar{bottom: 0px;}
		.jMensagemAlerta .mensagem > .alerta_continuar > a.btn{
			-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;padding: 5px 10px 2px;
			font-size: 14px;color: #fefefe;text-decoration: none!important;float: right;line-height: 20px;text-align: center;margin: 5px 10px;text-indent: 0px
		}
	</style>
	<script type="text/javascript">
		$(function(){
			$('.jMensagemAlerta .mensagem').not('.modelo').each(function(){
				$(this).overlay(
				{
					mascara: {
						color: '#000',
						loadSpeed: 200,
						opacity: 0.5
					},
					load:true,oneInstance: false}
			);
			});


		});
	</script>


	<div class="jMensagemAlerta">
		<? foreach ($this->mensagem as $tipo => $vMensagem): ?>
			<?
			switch ($tipo):
				case "sucesso":
					?>
					<div class="mensagem sucesso">
						<? foreach ($vMensagem as $mensagem): ?>	
							<div class="right">
								<h1>
									Sucesso!
								</h1>
								<p><?= $mensagem ?></p>
							</div>
							<div class="left">
								<img class="icone" src="/imagem/adm/icone/mensagem_icone_sucesso.png"/>
							</div>
						<? endforeach; ?>
						<div class="alerta_continuar"><a class="btn close" href="javascript:void(0)">Fechar</a></div>
					</div>
					<? break; ?>
				<? case "erro": ?>
					<div class="mensagem erro">
						<? foreach ($vMensagem as $mensagem): ?>
							<div class="right">
								<h1>
									Erro!
								</h1>
								<p><?= $mensagem ?></p>
							</div>
							<div class="left">
								<img class="icone" src="/imagem/adm/icone/mensagem_icone_erro.png"/>
							</div>
						<? endforeach; ?>
						<div class="alerta_continuar"><a class="btn close" href="javascript:void(0)">Fechar</a></div>
					</div>
					<? break; ?>
				<? default: ?>
					<div class="mensagem alerta">
						<? foreach ($vMensagem as $mensagem): ?>
							<div class="right">
								<h1>
									Alerta!
								</h1>
								<p><?= $mensagem ?></p>
							</div>
							<div class="left">
								<img class="icone" src="/imagem/adm/icone/mensagem_icone_alerta.png"/>
							</div>

						<? endforeach; ?>
						<div class="alerta_continuar"><a class="btn close" href="javascript:void(0)">Fechar</a></div>
					</div>
					<? break; ?>
			<? endswitch; ?>
		<? endforeach; ?>
	</div>
<? endif; ?>
