<!--[if lt IE 8]>
<div class="alert alert-warning">
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-xs-offset-3">
				<h2>Olá usuário,</h2>
				<p>Detectamos que o seu navegador utilizado está desatualizado. Por isso este e outros sites poderão apresentar problemas de visualização. Por isso recomendamos que você faça o download de um dos navegadores abaixo:</p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-2 col-xs-offset-3 text-center">
				<h4><a href="http://www.google.com/chrome?hl=pt" target="_blank">Chrome</a></h4>
				<p><a href="http://www.google.com/chrome?hl=pt" target="_blank"><img src="<?= $this->baseUrl('/imagem/library/chrome.png'); ?>" alt=""></a></p>
			</div>
			<div class="col-xs-2 text-center">
				<h4><a href="http://www.google.com/chrome?hl=pt" target="_blank">Firefox</a></h4>
				<p><a href="http://www.mozilla.com/firefox/" target="_blank"><img src="<?= $this->baseUrl('/imagem/library/firefox.png'); ?>" alt=""></a></p>
			</div>
			<div class="col-xs-2 text-center">
				<h4><a href="http://www.google.com/chrome?hl=pt" target="_blank">Internet Explorer</a></h4>
				<p><a href="http://windows.microsoft.com/pt-BR/internet-explorer/downloads/ie" target="_blank"><img src="<?= $this->baseUrl('/imagem/library/internet-explorer.png'); ?>" alt=""></a></p>
			</div>
		</div>
	</div>
</div>
<![endif]-->